FROM centos:7.5.1804

COPY ./fluig-installer /fluig

WORKDIR /fluig

RUN yum update -y && \
    yum install -y vim && \
    ./jdk-64/bin/java -cp fluig-installer.jar com.fluig.install.ExecuteInstall 

EXPOSE 80
EXPOSE 443

CMD ["sh", "/opt/fluig/appserver/bin/domain.sh"]